{% set name = "zaber-serial" %}
{% set version = "0.9.1" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/zaber.serial-{{ version }}.tar.gz
  sha256: 84e38c8761f976fa3f9481e5b977fab34d38e9df1949efb1a023da4b4c2a9a92

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
  run:
    - pyserial
    - python >={{ python_min }}

test:
  imports:
    - zaber
    - zaber.serial
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: http://www.zaber.com/support/docs/api/core-python/
  summary: A library for communicating with Zaber devices
  license: Apache-2.0
  license_file: LICENSE
  doc_url: https://www.zaber.com/support/docs/api/core-python/0.9.1/

extra:
  recipe-maintainers:
    - couger01
